# Generated by Django 3.2.13 on 2024-11-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maneja_iva', models.BooleanField(default=False)),
                ('porcentaje_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_ventas.cabeceraventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.producto')),
            ],
        ),
    ]
